apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
spec:
  ingressClassName: nginx
  rules:
    - host: a.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: simple
                port:
                  number: 80