apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: sre
  name: eureka
  labels:
    app: eureka
spec:
  serviceName: eureka
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: eureka
          image: eureka-server:v1.1
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_INSTANCE_HOST_NAME
              value: ${HOSTNAME}.eureka
            - name: EUREKA_INSTANCE_LIST
              value: http://eureka-0.eureka:8761/eureka/,http://eureka-1.eureka:8761/eureka/,http://eureka-2.eureka:8761/eureka/
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8761
            initialDelaySeconds: 30
            timeoutSeconds: 10