apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: registry.cn-hangzhou.aliyuncs.com/zdbc/envserver:v1.0
      envFrom:
      - configMapRef:
          name: special-config
  restartPolicy: Never
  imagePullSecrets:
    - name: regcred