apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      entrypoint: ["/bin/sh", "-c", "sleep", "36000"]
      envFrom:
      - configMapRef:
          name: special-config
  restartPolicy: Never