apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    app: centos
spec:
  containers:
    - name: centos
      image: centos
      command:
        - tail
        - -f
        - /dev/null
      imagePullPolicy: IfNotPresent
  restartPolicy: Always

