apiVersion: v1
kind: Pod
metadata:
  name: dnsutil
  labels:
    app: dnsutil
spec:
  containers:
    - name: dnsutil
      command:
        - tail
        - -f
        - /dev/null
      image: mydlqclub/dnsutils:1.3
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
