apiVersion: v1
kind: Pod
metadata:
  name: magick
  labels:
    app: magick
spec:
  containers:
    - name: magick
      image: dpokidov/imagemagick:7.1.0-16
      command:
        - tail
        - -f
        - /dev/null