apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', 'echo the app is running! && sleep 10']
      containers:
        - name: nginx
          image: nginx
