apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-anti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anti-nginx
  template:
    metadata:
      labels:
        app: anti-nginx
    spec:
      containers:
        - name: with-pod-affinity
          image: nginx
      affinity:
        podAffinity:
          requireDuringSchedulingIgnoreDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: a
                    operator: In
                    values:
                      - b
              topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
               matchExpressions:
                 - key: app
                   operator: In
                   values:
                     - anti-nginx


