apiVersion: v1
kind: Deployment
metadata:
  name: mysql-sre-database
  labels:
    app: mysql-sre

spec:
  selector:
    matchLabels:
      app: mysql-sre
  template:
    metadata:
      labels:
        app: mysql-sre
    spec:
      containers:
        - name: mysql
          image: mysql:5.7.33
          imagePullPolicy: IfNotPresent
          args:
            - --default_authentication_plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_c
          ports:
            - containerPort: 3306
              name: dbport
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 123456
            