apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-db-pv
  labels:
    type: local
spec:
  storageClassName: harbor-db
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-db-pvc
spec:
  storageClassName: harbor-db
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi