apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry-pv
  labels:
    type: local
spec:
  storageClassName: harbor-registry
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/registry"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-pvc
spec:
  storageClassName: harbor-registry
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi