apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deployment
spec:
  selector:
    matchLabels:
      app: httpserver
  replicas: 2
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: registry.cn-hangzhou.aliyuncs.com/zdbc/httpserver:v1.1
          ports:
            - containerPort: 9090
      imagePullSecrets:
        - name: regcred
