apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-sre
  namespace: sre

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName:
  storageClassName: nfs
