apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage-pv
  namespace: sre
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.112.4.sidecard
    path: "/data/mysqlstorage"
