apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-sre-database
  namespace: sre
  labels:
    app: mysql-sre

spec:
  selector:
    matchLabels:
      app: mysql-sre
  template:
    metadata:
      labels:
        app: mysql-sre
    spec:
      nodeSelector:
        disktype: ssd
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          args:
            - --default_authentication_plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
              name: dbport
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: mysql-sre
        - name: mysql-config
          configMap:
            name: mysql-config-sre
            