apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-pvc
  namespace: sre

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName:
  storageClassName: mysql-storage
