apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: sre
spec:
  storageClassName: nfs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.112.10
    path: "/nfs"
