apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  storageClassName: manual
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.16.112.10
    path: "/data/wordpressdata"